var a=[{img:"./kajai.jpg",name:"Kajal",price:199}]
[{img:"./kajai.jpg",name:"Kajal",price:199}]
[{img:"./kajai.jpg",name:"Kajal",price:199}]
[{img:"./kajai.jpg",name:"Kajal",price:199}]
[{img:"./kajai.jpg",name:"Kajal",price:199}]
[{img:"./kajai.jpg",name:"Kajal",price:199}]
[{img:"./kajai.jpg",name:"Kajal",price:199}]